---
title: "Incorporating micro-scale variation in macro-scale models"
author: "Laura Graham"
date: "28 September 2017"
output: html_document
bibliography: C:\Users\lg1u16\Documents\mendeley_bibtex\library.bib
---
```{r, echo=FALSE, include=FALSE}
```

# Introduction

<!-- overall this paragraph needs to be around why we would want to upscale, and why just aggregating is problematic. -->

Calls for greater integration of climate and land-use change in biodiversity and ecosystem service studies [@Titeux2017] mean a need for better methods to incorporate these data within the same models. Advances in remote sensing mean that increasing sources of data are available at fine spatial and temporal resolution yet broad extents. Macro-scale models, however, often require data to be aggregated to the lowest common resolution [@Guisan2005]. If we are to gain an understanding of broad-scale patterns in ecological processes, we may lose information on general patterns if we analyse these data at reduced extents; however, when upscaling these data to coarser resolutions, we lose information on the fine-scale processes [@Turner1989; @Kitron2006]. In this paper, we outline a method for upscaling fine-scale spatial data without losing information on spatial variation.

<!-- paragraph on why we lose information - Turner 89 and their solutions -->

Downgrading, or upscaling, the spatial resolution of data causes a loss of information about the structure of spatial features. For example, in landscape ecology Turner et al. [-@Turner1989] showed that ... . This issue is also apparent when considering abiotic features of the landscape; *geodiversity lit?*. A solution to this issue can be found within classes of metrics, such as FRAGSTATS [@McGarigal1994] or *geodiversity equivalent*.

<!-- Problem with metrics (subjective, too many correlated options, scale of organism not considered); gradient equivalent; likely gradient not taken up because of lack of statistical independence but offers a useful method for upscaling. -->

<!-- What have we done? -->

In this paper, we demonstrate a method that uses a moving window to calculate measures of spatial variability at a scale relevant to the process of interest. First, we present a simulation study to demonstrate how this method works for discrete and continuous variables. Next, we present two examples of this method applied to real data: (1) using information on habitat structure to improve habitat suitability models for *Garrulus glandarius* in the UK; (2) using information on topographic structure to improve predictions of plant species richness in ***. 

# Methods

## Moving window approach

We applied the moving window approach to a gridded surface; this could be in the form of spatial data (raster), or non-spatial data with a two-dimensial structure (i.e. a two-dimensional matrix). First we defined three scales: the grain, which is the characteristic scale of the predictor, typically the resolution of the input raster; the neighbourhood, which is a window representing the scale of effect between the predictor and the response; the extent, which is the resolution of the unit into which the response is predicted <!-- ref to figure from Macro poster -->. For each cell, we then calculated the a measure of variation in the input data for the neighbourhood  

## Simulation Study

### Discrete variables

### Continuous variables

## Case study 1: *Garrulus glandarius*

### Data



## Case study 2: Tree species richness

### Data


# Results

# Discussion

# Conclusion

# References